# Generated by Django 4.2.15 on 2024-09-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_categorias_prioridad'),
        ('profiles', '0005_profile_categorias_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suscripciones',
            field=models.ManyToManyField(blank=True, related_name='suscripciones', to='categories.categorias'),
        ),
    ]
