# Generated by Django 4.2.15 on 2024-09-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_categorias_pagas'),
        ('profiles', '0006_profile_suscripciones'),
    ]

    operations = [
    ]
