# Generated by Django 4.2.15 on 2024-09-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_merge_20240911_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='categorias_pagas',
        ),
    ]
