# Generated by Django 4.2.15 on 2024-09-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_contenido_cuerpo'),
        ('profiles', '0008_remove_profile_categorias_pagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contenidos_dislike',
            field=models.ManyToManyField(blank=True, related_name='contenidos_dislike', to='content.contenido'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contenidos_like',
            field=models.ManyToManyField(blank=True, related_name='contenidos_like', to='content.contenido'),
        ),
    ]
