version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/staticfiles
      - media-data:/uploads

  proxy:
    build:
      context: ./proxy
    restart: always
    volumes:
      - static-data:/staticfiles
      - media-data:/uploads
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  static-data:
  media-data: