# Generated by Django 5.1 on 2024-08-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=25, unique=True, verbose_name='Roles del Sistema')),
                ('rol_por_defecto', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, max_length=50)),
                ('permisos', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={},
        ),
    ]
