# Generated by Django 5.1 on 2024-08-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=25, unique=True, verbose_name='Roles del Sistema')),
                ('rol_por_defecto', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, max_length=50)),
                ('permisos', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'permissions': [('_crear_contenido', 'Crear Contenido'), ('_visualizar_contenido', 'Visualizar Contenido'), ('_editar_contenido', 'Editar Contenido'), ('_publicar_contenido', 'Publicar Contenido'), ('_rechazar_contenido', 'Rechazar Contenido'), ('_categoria_no_moderada', 'Categoria No Moderada'), ('_inactivar_contenido', 'Inactivar Contenido'), ('_cambiar_estado_contenido', 'Cambiar Estado Contenido'), ('_crear_rol', 'Crear Rol'), ('_modificar_rol', 'Modificar Rol'), ('_asignar_rol', 'Asignar Rol'), ('_remover_rol', 'Modificar Rol'), ('_eliminar_rol', 'Eliminar Rol'), ('_crear_categoria', 'Crear Categoria'), ('_modificar_categoria', 'Modificar Categoria'), ('_eliminar_categoria', 'Eliminar Categoria'), ('_inactivar_categoria', 'Inactivar Categoria'), ('_acceder_a_categoria_paga', 'Acceder a Categoria Paga'), ('_acceder_a_categoria_free', 'Acceder a Categoria Free'), ('_editar_perfil', 'Editar Perfil'), ('_suspender_cuenta', 'Suspender Cuenta'), ('_ver_tablero_kanban', 'Ver Tablero Kanban'), ('_modificar_tablero_kanban', 'Modificar Tablero Kanban'), ('_ver_reportes_contenido', 'Ver Reportes de Contenido'), ('_ver_estadisticas_contenido', 'Ver Estadisticas de Contenido'), ('_ver_cantidad_likes', 'Ver Cantidad de Likes'), ('_ver_cantidad_dislikes', 'Ver Cantidad de Dislikes'), ('_ver_cantidad_visualizaciones', 'Ver Cantidad de visualizaciones'), ('_ver_cantidad_compartidos', 'Ver Cantidad de Compartidos'), ('_comentar_contenido', 'Comentar Contenido'), ('_eliminar_contenido', 'Eliminar Contenido'), ('_reportar_contenido', 'Reportar Contenido'), ('_compartir_contenido', 'Compartir Contenido'), ('_filtrar_por_categoria', 'Filtrar por Categoria'), ('_filtrar_por_autor', 'Filtrar por Autor'), ('_filtrar_por_tags', 'Filtrar por Tags'), ('_modificar_estado_contenido', 'Modificar Estado de Contenido'), ('_administrar_estado_contenido', 'Administrar Estado de Contenido'), ('_eliminar_estado_contenido', 'Eliminar Estado de Contenido'), ('_visualizar_versiones_contenido', 'Visualizar versiones de Contenido'), ('_restaurar_verisiones_contenido', 'Restaurar Versiones de Contenido')],
            },
        ),
    ]
