# Generated by Django 5.1 on 2024-08-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='precio',
            field=models.IntegerField(default=20000, null=True),
        ),
    ]
