# Generated by Django 5.1 on 2024-08-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categorias_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
