# Generated by Django 5.1 on 2024-08-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_categorias_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'default_permissions': ()},
        ),
    ]
