# Generated by Django 4.2.15 on 2024-09-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_categorias_moderada'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='prioridad',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
