# Generated by Django 4.2.15 on 2024-09-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_categorias_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='prioridad',
            field=models.BooleanField(default=False),
        ),
    ]
