# Generated by Django 4.2.15 on 2024-09-04 20:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='cuerpo', null=True),
        ),
    ]
