# Generated by Django 4.2.15 on 2024-09-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_valoracion_usuario_contenidoseleccionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='fecha_publicacion',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='vigencia',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='fecha_publicacion',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='vigencia',
            field=models.DateField(default=None, null=True),
        ),
    ]
