# Generated by Django 4.2.15 on 2024-09-10 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_contenido_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
