# Generated by Django 4.2.15 on 2024-09-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contenidoreportado_email'),
        ('content', '0008_alter_contenido_fecha_publicacion_and_more'),
    ]

    operations = [
    ]
