# Generated by Django 4.2.15 on 2024-09-11 15:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_merge_20240911_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='\n        <p><span style="font-family:Times New Roman,Times,serif"><span style="font-size:20px">Cuerpo del contenido</span></span></p>\n\n        <p><span style="font-family:Times New Roman,Times,serif"><span style="font-size:20px">opcional:image</span></span></p>\n\n        <p><span style="font-family:Times New Roman,Times,serif"><span style="font-size:20px">opcional:embedido youtube</span></span></p>\n\n        <p><span style="font-family:Times New Roman,Times,serif"><span style="font-size:18px"><strong>Tags: <span style="color:#3498db">#Tag1 #Tag2 #Tag3</span></strong></span></span></p>\n        ', null=True),
        ),
    ]
