# Generated by Django 4.2.15 on 2024-09-20 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0010_alter_contenido_cuerpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior_estado', models.CharField(max_length=10)),
                ('nuevo_estado', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('contenido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.contenido')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
