# Generated by Django 4.2.15 on 2024-09-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_statuschangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='cantidad_compartidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
