# Generated by Django 4.2.15 on 2024-10-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_contenido_cantidad_compartidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
